site_name: SWD7 - Introduction to Data Visualisation in Python

repo_url: https://github.com/ARCTraining/python-project-template
repo_name: Python Project Template

copyright: By University of Leeds Research Computing Team, Copyright &copy; 2024

theme:
  name: "material"
  custom_dir: overrides
  icon:
    repo: fontawesome/brands/github
  features:
    - content.code.copy
    - navigation.footer
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

plugins:
- mkdocs-jupyter:
    ignore_h1_titles: True
    include_source: True
#   - search
#   - toggle-sidebar
#   - awesome-pages
#   - mermaid2:
#       arguments:
#         theme: 'base'

markdown_extensions:
  - pymdownx.arithmatex:
        generic: true
        block_tag: 'pre'
  - pymdownx.details
  - pymdownx.tilde
  - pymdownx.snippets
  - admonition
  - pymdownx.blocks.tab
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true


nav:
  - Course content: index.md
  - Introduction: 00-Introduction.md
  - 5 Key Concepts:
    - 1. Audience: 01-Audience.md
    - 2. Story: 02-Story.md
    - 3. Encoding: 03-Encoding.md
    - 4. Composition: 04-Composition.md
    - 5. Simplify: 05-Simplify.md
  - Practical Session:
    - How to use this resource: nbs/00_explanation.md
    - 1. Introduction notebook: nbs/01_datavis_solutions.ipynb
    - 2. Other libraries notebook: nbs/02_datavis_solutions.ipynb